#if !canImport(ObjectiveC)
import XCTest

extension AELogTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AELogTests = [
        ("testLogPerformance", testLogPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AELogTests.__allTests__AELogTests),
    ]
}
#endif
